Project Name: EECS 690 Mini-Project 03

Purpose: Evaluate patterns in avocado prices, and changes in sea surface temperature

Input(s):   avocado_prices.csv

            departure_bay_temperature.csv - DFO Pacific Biological Station

Output(s):  Multiple scatter plots of avocado data

            Faceted plots of temperature data

Author: Jacob Kice

Initial Date: 02/21/2026

Updated Date: 02/21/2026

Import packages

In [79]:
import pandas as pd
import altair as alt

Load and check avocado data

In [80]:
avocado_prices = pd.read_csv("data/avocado_prices.csv") # Read csv
avocado_prices  #Display df

,Date,average_price,small_hass_volume,large_hass_volume,extra_l_hass_volume,type,yr,region,wk
0,2015-12-27,1.33,1036.74,54454.85,48.16,conventional,2015,Albany,52
1,2015-12-20,1.35,674.28,44638.81,58.33,conventional,2015,Albany,51
2,2015-12-13,0.93,794.70,109149.67,130.50,conventional,2015,Albany,50
3,2015-12-06,1.08,1132.00,71976.41,72.58,conventional,2015,Albany,49
4,2015-11-29,1.28,941.48,43838.39,75.78,conventional,2015,Albany,48
...,...,...,...,...,...,...,...,...,...
17906,2018-02-04,1.63,2046.96,1529.20,0.00,organic,2018,WestTexNewMexico,5
17907,2018-01-28,1.71,1191.70,3431.50,0.00,organic,2018,WestTexNewMexico,4
17908,2018-01-21,1.87,1191.92,2452.79,727.94,organic,2018,WestTexNewMexico,3
17909,2018-01-14,1.93,1527.63,2981.04,727.01,organic,2018,WestTexNewMexico,2
17910,2018-01-07,1.62,2894.77,2356.13,224.53,organic,2018,WestTexNewMexico,1

Plot average price vs date

In [81]:
alt.data_transformers.disable_max_rows()    # Disable max rows error message to allow plotting of all data

DataTransformerRegistry.enable('default')

In [82]:
avocado_plot = alt.Chart(avocado_prices).mark_point().encode(   # Initialize scatter plot for avocado prices
    x=alt.X("Date"),                    # Set x-axis as Date column
    y=alt.Y("average_price")            # Set y-axis as average price column
        .title("Average Price")         # Set title of y-axis
).configure_axis(                       # Configure font sizes for axes
    labelFontSize=12,
    titleFontSize=12
).properties(                           # Set plot title
    title="Avocado Average Price"
)
avocado_plot                            # Display plot

alt.Chart(...)

Aggregate by week

In [83]:

avocado_aggregate = avocado_prices.groupby("wk").mean(numeric_only=True).reset_index()  # Aggregate df by week column, 
                                                                                        # calculate aggregated averages
avocado_aggregate           # Display aggregated df

,wk,average_price,small_hass_volume,large_hass_volume,extra_l_hass_volume,yr
0,1,1.286887,191342.390307,218561.677642,14571.720660,2016.500000
1,2,1.330519,180736.856368,205410.353231,13433.732241,2016.500000
2,3,1.341415,186900.340259,210345.864906,14890.573939,2016.500000
3,4,1.315047,183383.858160,206762.362052,14990.596557,2016.500000
4,5,1.253608,250123.511250,258856.288561,19160.686274,2016.500000
5,6,1.235401,258649.665873,265093.593939,21991.637052,2016.500000
6,7,1.301038,202504.197712,186915.602712,15935.870283,2016.500000
7,8,1.318703,182749.072052,179621.072925,15079.317170,2016.500000
8,9,1.293915,201307.586745,202320.651627,16035.863325,2016.500000
9,10,1.311863,191553.633396,182778.084906,15725.715330,2016.500000
10,11,1.336415,188943.209104,180820.456132,15697.008090,2016.500000
11,12,1.342123,189398.188113,195371.034835,16472.400259,2016.500000
12,13,1.350660,180864.786195,183525.053805,17035.197956,2016.000000
13,14,1.367013,190499.043522,177845.266981,16609.558868,2016.000000
14,15,1.336635,201068.488522,182330.586321,16203.862547,2016.000000
15,16,1.367736,195840.742767,189830.423679,18356.412893,2016.000000
16,17,1.375377,198063.766132,193759.506730,16245.495189,2016.000000
17,18,1.334874,231280.938365,236721.278239,16970.315377,2016.000000
18,19,1.313270,241199.419969,245303.841132,19522.075503,2016.000000
19,20,1.367516,202647.572233,191025.317925,17658.131289,2016.000000
20,21,1.390031,202376.432799,193746.797736,16836.583050,2016.000000
21,22,1.404151,214278.927579,197993.141321,16969.922327,2016.000000
22,23,1.397421,222275.518742,195609.767642,18908.450000,2016.000000
23,24,1.409308,215342.968742,186258.429843,17597.914371,2016.000000
24,25,1.409117,211747.530757,201571.342019,19650.433502,2015.996845
25,26,1.425489,196880.533849,186520.042114,17432.464416,2015.996845
26,27,1.429277,209992.722987,204917.236887,20501.201730,2016.000000
27,28,1.439717,188170.984057,187477.774214,16070.822170,2016.000000
28,29,1.468145,176153.288270,183669.142138,15102.643742,2016.000000
29,30,1.491824,174749.986509,181551.093899,13629.104371,2016.000000
30,31,1.501792,171765.361321,179934.614874,12550.030755,2016.000000
31,32,1.487642,188391.508302,190307.955943,12983.963994,2016.000000
32,33,1.504717,184880.026604,187362.218994,13452.197358,2016.000000
33,34,1.533648,177289.569151,168192.070912,11299.131101,2016.000000
34,35,1.542704,179105.436887,167092.769214,11535.917704,2016.000000
35,36,1.554843,189787.238176,181867.359591,11970.250597,2016.000000
36,37,1.555629,165802.983396,181973.614748,11484.363239,2016.000000
37,38,1.576730,152466.407925,169935.980409,10918.819906,2016.000000
38,39,1.607453,141891.530692,169201.958679,10448.143396,2016.000000
39,40,1.623365,134308.609308,168945.425157,11172.994497,2016.000000
40,41,1.567704,138993.627421,165234.511258,13245.643050,2016.000000
41,42,1.554434,137368.303365,171445.592579,11054.719843,2016.000000
42,43,1.530346,132100.532893,152575.992358,11073.834151,2016.000000
43,44,1.536604,142509.974717,169159.397296,12320.008868,2016.000000
44,45,1.505503,147735.435755,157813.995157,11025.329969,2016.000000
45,46,1.478774,152287.273679,159867.152610,9297.375912,2016.000000
46,47,1.444434,144861.212704,143292.346132,8782.453711,2016.000000
47,48,1.448365,129288.635503,129185.417421,7870.755252,2016.000000
48,49,1.349369,164496.421199,178499.308360,10376.274006,2016.003155
49,50,1.314088,156001.794371,177274.114277,9754.610786,2016.000000
50,51,1.331887,146276.929717,161511.456132,11612.949434,2016.000000
51,52,1.350881,147530.938176,158046.367296,12141.487767,2016.000000
52,53,1.284151,197566.661132,213168.933302,10238.492547,2017.000000

Plot average price by week

In [84]:
aggregate_week_plot = alt.Chart(avocado_aggregate).mark_point().encode( # Initialize scatter plot for aggregated avocado prices
    x=alt.X("wk", title="Week"),                    # Set x-axis as week column
    y=alt.Y("average_price")                        # Set y-axis as average price column
        .title("Average Price (in US Dollars)")     # Set title of y-axis
        .scale(zero=False)                          # Set scale of y-axis to not start at zero
).configure_axis(                                   # Configure font sizes for axes
    labelFontSize=12,
    titleFontSize=12
).properties(                                       # Set plot title
    title="Avocado Average Price per Week"
)
aggregate_week_plot                                 # Display plot

alt.Chart(...)

Calculate total volume - sum of three volume columns - original avocado data frame

In [85]:
avocado_prices_total_volume = avocado_prices.assign(    # Create new df with new column
    total_volume=avocado_prices.loc[                    # New column is named total_volume
        :, avocado_prices.columns.str.contains('volume')].sum(axis=1)   # Select all rows,
                                                                        # only columns where name contains volume,
                                                                        # sum each row, assign to new column 
)
avocado_prices_total_volume     # Display df

,Date,average_price,small_hass_volume,large_hass_volume,extra_l_hass_volume,type,yr,region,wk,total_volume
0,2015-12-27,1.33,1036.74,54454.85,48.16,conventional,2015,Albany,52,55539.75
1,2015-12-20,1.35,674.28,44638.81,58.33,conventional,2015,Albany,51,45371.42
2,2015-12-13,0.93,794.70,109149.67,130.50,conventional,2015,Albany,50,110074.87
3,2015-12-06,1.08,1132.00,71976.41,72.58,conventional,2015,Albany,49,73180.99
4,2015-11-29,1.28,941.48,43838.39,75.78,conventional,2015,Albany,48,44855.65
...,...,...,...,...,...,...,...,...,...,...
17906,2018-02-04,1.63,2046.96,1529.20,0.00,organic,2018,WestTexNewMexico,5,3576.16
17907,2018-01-28,1.71,1191.70,3431.50,0.00,organic,2018,WestTexNewMexico,4,4623.20
17908,2018-01-21,1.87,1191.92,2452.79,727.94,organic,2018,WestTexNewMexico,3,4372.65
17909,2018-01-14,1.93,1527.63,2981.04,727.01,organic,2018,WestTexNewMexico,2,5235.68
17910,2018-01-07,1.62,2894.77,2356.13,224.53,organic,2018,WestTexNewMexico,1,5475.43

Aggregate updated dataset by week

In [86]:
avocado_aggregate_2 = avocado_prices_total_volume.groupby("wk").mean(numeric_only=True).reset_index()   # Aggregate df by week column,
                                                                                                        # calculate aggregated averages
avocado_aggregate_2         # Display aggregated df

,wk,average_price,small_hass_volume,large_hass_volume,extra_l_hass_volume,yr,total_volume
0,1,1.286887,191342.390307,218561.677642,14571.720660,2016.500000,424475.788608
1,2,1.330519,180736.856368,205410.353231,13433.732241,2016.500000,399580.941840
2,3,1.341415,186900.340259,210345.864906,14890.573939,2016.500000,412136.779104
3,4,1.315047,183383.858160,206762.362052,14990.596557,2016.500000,405136.816769
4,5,1.253608,250123.511250,258856.288561,19160.686274,2016.500000,528140.486085
5,6,1.235401,258649.665873,265093.593939,21991.637052,2016.500000,545734.896863
6,7,1.301038,202504.197712,186915.602712,15935.870283,2016.500000,405355.670708
7,8,1.318703,182749.072052,179621.072925,15079.317170,2016.500000,377449.462146
8,9,1.293915,201307.586745,202320.651627,16035.863325,2016.500000,419664.101698
9,10,1.311863,191553.633396,182778.084906,15725.715330,2016.500000,390057.433632
10,11,1.336415,188943.209104,180820.456132,15697.008090,2016.500000,385460.673325
11,12,1.342123,189398.188113,195371.034835,16472.400259,2016.500000,401241.623208
12,13,1.350660,180864.786195,183525.053805,17035.197956,2016.000000,381425.037956
13,14,1.367013,190499.043522,177845.266981,16609.558868,2016.000000,384953.869371
14,15,1.336635,201068.488522,182330.586321,16203.862547,2016.000000,399602.937390
15,16,1.367736,195840.742767,189830.423679,18356.412893,2016.000000,404027.579340
16,17,1.375377,198063.766132,193759.506730,16245.495189,2016.000000,408068.768050
17,18,1.334874,231280.938365,236721.278239,16970.315377,2016.000000,484972.531981
18,19,1.313270,241199.419969,245303.841132,19522.075503,2016.000000,506025.336604
19,20,1.367516,202647.572233,191025.317925,17658.131289,2016.000000,411331.021447
20,21,1.390031,202376.432799,193746.797736,16836.583050,2016.000000,412959.813585
21,22,1.404151,214278.927579,197993.141321,16969.922327,2016.000000,429241.991226
22,23,1.397421,222275.518742,195609.767642,18908.450000,2016.000000,436793.736384
23,24,1.409308,215342.968742,186258.429843,17597.914371,2016.000000,419199.312956
24,25,1.409117,211747.530757,201571.342019,19650.433502,2015.996845,432969.306278
25,26,1.425489,196880.533849,186520.042114,17432.464416,2015.996845,400833.040379
26,27,1.429277,209992.722987,204917.236887,20501.201730,2016.000000,435411.161604
27,28,1.439717,188170.984057,187477.774214,16070.822170,2016.000000,391719.580440
28,29,1.468145,176153.288270,183669.142138,15102.643742,2016.000000,374925.074151
29,30,1.491824,174749.986509,181551.093899,13629.104371,2016.000000,369930.184780
30,31,1.501792,171765.361321,179934.614874,12550.030755,2016.000000,364250.006950
31,32,1.487642,188391.508302,190307.955943,12983.963994,2016.000000,391683.428239
32,33,1.504717,184880.026604,187362.218994,13452.197358,2016.000000,385694.442956
33,34,1.533648,177289.569151,168192.070912,11299.131101,2016.000000,356780.771164
34,35,1.542704,179105.436887,167092.769214,11535.917704,2016.000000,357734.123805
35,36,1.554843,189787.238176,181867.359591,11970.250597,2016.000000,383624.848365
36,37,1.555629,165802.983396,181973.614748,11484.363239,2016.000000,359260.961384
37,38,1.576730,152466.407925,169935.980409,10918.819906,2016.000000,333321.208239
38,39,1.607453,141891.530692,169201.958679,10448.143396,2016.000000,321541.632767
39,40,1.623365,134308.609308,168945.425157,11172.994497,2016.000000,314427.028962
40,41,1.567704,138993.627421,165234.511258,13245.643050,2016.000000,317473.781730
41,42,1.554434,137368.303365,171445.592579,11054.719843,2016.000000,319868.615786
42,43,1.530346,132100.532893,152575.992358,11073.834151,2016.000000,295750.359403
43,44,1.536604,142509.974717,169159.397296,12320.008868,2016.000000,323989.380881
44,45,1.505503,147735.435755,157813.995157,11025.329969,2016.000000,316574.760881
45,46,1.478774,152287.273679,159867.152610,9297.375912,2016.000000,321451.802201
46,47,1.444434,144861.212704,143292.346132,8782.453711,2016.000000,296936.012547
47,48,1.448365,129288.635503,129185.417421,7870.755252,2016.000000,266344.808176
48,49,1.349369,164496.421199,178499.308360,10376.274006,2016.003155,353372.003565
49,50,1.314088,156001.794371,177274.114277,9754.610786,2016.000000,343030.519434
50,51,1.331887,146276.929717,161511.456132,11612.949434,2016.000000,319401.335283
51,52,1.350881,147530.938176,158046.367296,12141.487767,2016.000000,317718.793239
52,53,1.284151,197566.661132,213168.933302,10238.492547,2017.000000,420974.086981

Plot aggregated total volume

In [87]:
aggregate_total_volume_plot = alt.Chart(avocado_aggregate_2).mark_point().encode(   # Initialize scatter plot for aggregated data
    x=alt.X("wk", title="Week"),                        # Set x-axis as week column
    y=alt.Y("total_volume")                             # Set y-axis as total volume column
        .title("Average Total Volume (lbs)")            # Set title of y-axis
        .scale(zero=False)                              # Set y-axis to not start at zero
).configure_axis(                                       # Configure font sizes for axes
    labelFontSize=12,
    titleFontSize=12
).properties(                                           # Set plot title
    title="Avocado Average Total Volume per Week"
)
aggregate_total_volume_plot                             # Display plot

alt.Chart(...)

Load and display departure bay temperature data

In [88]:
departure_bay_temperature = pd.read_csv("data/departure_bay_temperature.csv", skiprows=2)   # Read data,
                                                                                            # skip two rows of metadata
departure_bay_temperature           # Display df

     Year  Jan  Feb  Mar  Apr   May   Jun   Jul   Aug   Sep   Oct  Nov  Dec
0    1914  7.2  NaN  NaN  NaN   NaN   NaN   NaN   NaN  11.1  10.0  7.3  6.3
1    1915  5.6  6.6  7.5  9.0   9.9  12.5  14.7  15.8  14.0   8.2  4.4  4.1
2    1916  1.2  0.1  3.5  6.5   8.0  12.0  13.1  14.0  11.4   7.6  5.4  3.5
3    1917  3.8  2.8  4.4  5.4   8.3  11.0  13.7  12.2  10.0   8.6  7.0  4.9
4    1918  3.7  3.9  4.6  6.0   9.3  11.2  13.1  14.5  13.8   9.1  6.7  5.0
..    ...  ...  ...  ...  ...   ...   ...   ...   ...   ...   ...  ...  ...
100  2014  4.4  3.1  3.7  7.7  10.1  12.0  15.9  16.8  11.7  10.6  7.1  7.1
101  2015  6.3  8.0  8.0  8.9  11.0  15.5  13.8  13.4  11.6  11.3  8.1  6.8
102  2016  6.0  7.1  8.4  9.8  13.0  14.2  14.6  14.6  12.6  10.8  8.2  5.5
103  2017  5.6  4.8  7.1  7.9  10.5  12.4  15.3  15.3  13.1  10.2  8.8  6.9
104  2018  6.2  6.0  7.1  8.2   NaN   NaN   NaN   NaN   NaN   NaN  NaN  NaN

[105 rows x 13 columns]

Use melt to reshape dataframe

In [89]:
departure_bay_temperature = departure_bay_temperature.melt(     # Modify df with melt function
    id_vars="Year",                 # Set year column as id variable, to be used as row identifier
    var_name="Month",               # Set month column as variable name, name to use for column holding old column names
    value_name="Temperature"        # Set value name as temperature, for column to hold 'melted' values
)
departure_bay_temperature           # Display modified df

      Year Month  Temperature
0     1914   Jan          7.2
1     1915   Jan          5.6
2     1916   Jan          1.2
3     1917   Jan          3.8
4     1918   Jan          3.7
...    ...   ...          ...
1255  2014   Dec          7.1
1256  2015   Dec          6.8
1257  2016   Dec          5.5
1258  2017   Dec          6.9
1259  2018   Dec          NaN

[1260 rows x 3 columns]

Plot average temperature vs year for the month of November

In [90]:
november_temp_plot = alt.Chart(         # Initialize scatter plot
    departure_bay_temperature[departure_bay_temperature["Month"] == "Nov"]).mark_point().encode(    # Select input from rows
                                                                                                    # where month is November
    x=alt.X("Year")                                                 # Set x-axis as year column
        .title("Year")                                              # Set title of x-axis
        .scale(zero=False),                                         # Set x-axis to not start at zero
    y=alt.Y("Temperature")                                          # Set y-axis as temperature column
        .title("Temperature (Celsius)")                             # Set title of y-axis
        .scale(zero=False)                                          # Set y-axis to not start at zero
).configure_axis(                                                   # Configure font sizes of axes
    labelFontSize=12,
    titleFontSize=12
).properties(                                                       # Set plot title
    title="Departure Bay Temperature Monthly Average (November)"
)
november_temp_plot                                                  # Display plot

alt.Chart(...)

Plot average temp vs year for all months, in faceted display

In [91]:
all_temp_plot = alt.Chart(departure_bay_temperature).mark_point().encode(   # Initialize scatter plot
    x=alt.X("Year")                                                         # Set x-axis as year column
        .title("Year")                                                      # Set title of x-axis
        .scale(zero=False),                                                 # Set x-axis to not start at zero
    y=alt.Y("Temperature")                                                  # Set y-axis as temperature column
        .title("Temperature (Celsius)")                                     # Set title of y-axis
        .scale(zero=False)                                                  # Set y-axis to not start at zero
).facet(                                                                    # Plot subsets (facets) of the data in separate subplots
    "Month",                                                                # Facet data by month value
    columns=4                                                               # Plot facets in four columns
).configure_axis(                                                           # Configure font sizes of axes
    labelFontSize=12,
    titleFontSize=12
).properties(                                                               # Set plot title
    title="Departure Bay Temperature Monthly Average (All Months)"
)
all_temp_plot                                                               # Display plot

alt.FacetChart(...)